### ISSUE TITLE
Arms bone error.

### ISSUE THREAD

**Issue by whitestarlau** [bkevelham/unity-avatar-generation#1]
I created the avatar model on the readyplayer.me website, and then imported it into my project using blender. Now I want to create my unity avatar at runtime. The name of the model bone created on the website is as shown in the picture below, so I modified the hardcoding. But I found that the bone of the arm part is always wrong, and the effect is as shown in the picture. I repeatedly checked and found that the bone orientation of the avatar arm part created on this website is different from the example you gave. How do I need to fix this problem?

![shoot3](https://github.com/bkevelham/unity-avatar-generation/assets/9989324/e06ec5b0-aad5-4a33-a8dd-b8e411577646)

![shoot2](https://github.com/bkevelham/unity-avatar-generation/assets/9989324/39b22922-d082-4817-b5a6-01ad743d3a5c)
![shoot1](https://github.com/bkevelham/unity-avatar-generation/assets/9989324/ec2be048-6b0e-42c8-a087-9b320a9783cf)

**Comment by bkevelham** [comment]
Hi there,

it is somewhat difficult to say, but are you sure your new model is standing in a T-Pose when the Avatar is generated? 
As the instructions on the HumanoidAvatarBuilder say, that is required for this code to work.

**Comment by whitestarlau** [comment]
Thanks for your reply. I found that the model loaded with GLTFUtility is not T-Pose by default. I will try to find out how to modify it to T-Pose.
![屏幕截图 2023-09-06 112336](https://github.com/bkevelham/unity-avatar-generation/assets/9989324/17d9fa75-b75e-47bf-8036-6e36728851f7)

**Comment by whitestarlau** [comment]
I modify LeftArm and RightArm rotation before build Avatar,then the problem is fixed.Thank you!
By the way, I use the following code to fix the model to T-pose:
``` CSharp
    private static void FixTPose(GameObject avatarRoot)
    {
        Transform[] avatarTransforms = avatarRoot.GetComponentsInChildren<Transform>();
        foreach (Transform avatarTransform in avatarTransforms)
        {
            if (avatarTransform.name.Equals("RightArm"))
            {
                Quaternion old = avatarTransform.rotation;
                Debug.Log("FixTPose RightArm old:" + old);
                avatarTransform.rotation = new Quaternion(-0.46708f, -0.50621f, 0.55205f, -0.46992f);
                Debug.Log("FixTPose RightArm new:" + avatarTransform.rotation);
            }
             if (avatarTransform.name.Equals("LeftArm"))
            {
                Quaternion old = avatarTransform.rotation;
                Debug.Log("FixTPose LeftArm old:" + old);
                avatarTransform.rotation = new Quaternion(0.46708f, -0.50621f, 0.55205f, 0.46992f);
                Debug.Log("FixTPose LeftArm new:" + avatarTransform.rotation);
            }
        }
    }
```

**Comment by bkevelham** [comment]
Glad to see you've solved it.
